# Grafana Storage
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      app: my-grafana
