# Prometheus Storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: monitoring 
  labels:
    app: my-prometheus
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: your_server
    path: "/data"
